### ISSUE TITLE
O3.1 Automated Hyperparameter learning for Random Feature emulators

### ISSUE THREAD

**Issue by odunbar** [CliMA/CalibrateEmulateSample.jl#231]
```[tasklist]
### Tasks
- [ ] https://github.com/CliMA/CalibrateEmulateSample.jl/issues/228
- [ ] https://github.com/CliMA/CalibrateEmulateSample.jl/issues/229
- [ ] https://github.com/CliMA/CalibrateEmulateSample.jl/issues/230
- [ ] https://github.com/CliMA/CalibrateEmulateSample.jl/issues/215
```
